source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Fairy Bread' do
	pod 'PureLayout'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FontAwesomeKit'
    pod 'CustomIOSAlertView', '~> 0.9.5'
end
